### PR TITLE
Admin menu

### PR DESCRIPTION
**Pull request by nate-li**
# Conflicts:
#	tinker/publish/views.py

### CODE REVIEW

**Comment by e-jameson** [comment]
@nate-li can you go ahead and move these into different blueprints all inside the `admin` folder (sorry!). Stop by and talk to either @c-schwarze or myself and we can show you how we'd like it organized.

**Comment by c-schwarze** [comment]
Looks good to me.

**Comment by e-jameson** [comment]
:+1: :shipit:

**Comment by c-schwarze** [comment]
Okay, I pulled the code live.

@nate-li could you click around on tinker.bethel.edu to see if its working correctly?

**Pull request merged**
