### PR TITLE
Program search fixes

### PR DESCRIPTION
**Pull request by c-schwarze**

### CODE REVIEW

**Comment by c-schwarze** [comment]
failed units tests :(

**Comment by c-schwarze** [comment]
@phg49389 I fixed one of the unit test issues. Can you take a look at this other one?

test_get_program_name_valid is failing.

**Comment by phg49389** [comment]
Looking into it now

**Comment by phg49389** [comment]
I don't think that this error is from _your_ changes, @c-schwarze 

I'll keep investigating

**Comment by phg49389** [comment]
It looks like Data Definitions/Portal/Tab in Cascade got renamed to Data Definitions/Portal/Page, so now Tab != Page. I updated the unit test accordingly and now it works.

**Comment by c-schwarze** [comment]
ah. that makes sense. Thanks

**Pull request merged**
