### PR TITLE
Roles table

### PR DESCRIPTION
**Pull request by nate-li**

### CODE REVIEW

**Comment by c-schwarze** [comment]
@nate-li could you merge with master? click on "Update from master" on the github desktop?

It will update your pull request with the master's commits.

**Comment by e-jameson** [comment]
@c-schwarze what do you think about storing all the "admin" things under one blueprint, so we don't end up with a large amount of top level folders in the project?

**Comment by c-schwarze** [comment]
Nathan is going to do that next time he is in.

**Comment by e-jameson** [comment]
Oh okay, cool.

**Comment by e-jameson** [comment]
API-12 Testing something, ignore this

**Comment by c-schwarze** [comment]
Oh, also, @nate-li, the code looks good. 

Does this need to be in the views.py file? It looks like you aren't using it:
```
"""@blink_roles_blueprint.route('/role/<uid>/<portal>')
def role_redirect():
    uid_list = uid
    portal_list = portal"""
```

**Comment by e-jameson** [comment]
Does this do any security checking based on groups or roles, etc to restrict access? Even if the Admin nav item does it, it might be smart to check before each request. I believe we can do something like

`@blueprint_name.before_request` just like we do `@app.before_request` so it checks it before any request to the admin blueprint.

**Comment by e-jameson** [comment]
Closing as this overlaps with #110

**Pull request closed without merging**
